export const TREATMENTS = [

  // ─── SKIN TREATMENTS ────────────────────────────────────────────────────────
  {
    id: 1,
    category: 'Skin',
    name: "Signature Facial",
    price: "£95",
    time: "60 mins",
    image: "/images/facial.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Our bespoke facial designed to deep cleanse, exfoliate and nourish your skin. Tailored every time to your unique skin type using professional CosMedix clinical products.",
    products: "CosMedix Benefit Clean, Purity Solution, Refine",
    results: "Immediate glow, smoother texture and deeply hydrated skin.",
  },
  {
    id: 2,
    category: 'Skin',
    name: "Signature Facial + LED",
    price: "£120",
    time: "75 mins",
    image: "/images/facial.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Our signature facial enhanced with LED Light Therapy for deeper cellular rejuvenation and radiance.",
    products: "CosMedix + LED Light Therapy",
    results: "Boosted collagen production, reduced redness and enhanced glow.",
  },
  {
    id: 3,
    category: 'Skin',
    name: "Chemical Peel",
    price: "£99",
    time: "45 mins",
    image: "/images/chemical.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Medical-grade CosMedix metabolic peels to resurface, renew and brighten the skin. Safe for all skin types and tailored to your concern.",
    products: "CosMedix Metabolic Peels",
    results: "Improved skin tone, smoother texture and reduced fine lines.",
  },
  {
    id: 4,
    category: 'Skin',
    name: "Microneedling",
    price: "£110",
    time: "60 mins",
    image: "/skincare/microneedling.png",
    modalImage: "/skincare/before-after.png",
    description: "Collagen Induction Therapy using precise micro-channels to stimulate your skin's natural healing and renewal process.",
    products: "Sterile Micro-needling Technology + Serums",
    results: "Firmer, plumper skin with visibly reduced acne scars and fine lines.",
  },
  {
    id: 5,
    category: 'Skin',
    name: "Hydrafacial",
    price: "£110",
    time: "60 mins",
    image: "/images/facial.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Deeply cleanses, extracts and hydrates using patented vortex-fusion technology. One of our most popular treatments for instant visible results.",
    products: "Vortex-Fusion Technology Serums",
    results: "Deeply cleaned pores and an instant 'glass skin' finish.",
  },
  {
    id: 6,
    category: 'Skin',
    name: "Dermaplaning",
    price: "£65",
    time: "45 mins",
    image: "/images/facial.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Precise removal of dead skin cells and fine vellus hair using a surgical-grade blade, leaving your skin silky smooth.",
    products: "Surgical-grade Blade & Hydrating Mask",
    results: "Better product absorption, smoother skin and a flawless makeup base.",
  },
  {
    id: 7,
    category: 'Skin',
    name: "LED Light Therapy",
    price: "£40",
    time: "30 mins",
    image: "/images/dermalux.png",
    modalImage: "/skincare/before-after.png",
    description: "Clinically proven multi-wavelength light therapy that rejuvenates, repairs and calms all skin types with zero downtime.",
    products: "Multi-wavelength LED Technology",
    results: "Calmed inflammation, boosted collagen and improved overall skin health.",
  },
  {
    id: 8,
    category: 'Skin',
    name: "Skin Tag Removal",
    price: "from £40",
    time: "30 mins",
    image: "/images/analysis.png",
    modalImage: "/skincare/before-after.png",
    description: "Safe and precise removal of unwanted skin tags using medical-grade tools in a clinical setting.",
    products: "Medical Extraction Tools",
    results: "Clear, smooth skin surface with no trace of the skin tag.",
  },
  {
    id: 9,
    category: 'Skin',
    name: "Milia Removal",
    price: "from £50",
    time: "30 mins",
    image: "/images/analysis.png",
    modalImage: "/skincare/before-after.png",
    description: "Professional extraction of white keratin-filled milia seeds, commonly found around the eye and cheek area.",
    products: "Sanitised Precision Extraction Tools",
    results: "Smooth, bump-free skin around the eyes and face.",
  },
  {
    id: 10,
    category: 'Skin',
    name: "Cherry Angioma Removal",
    price: "from £40",
    time: "30 mins",
    image: "/images/analysis.png",
    modalImage: "/skincare/before-after.png",
    description: "Safe removal of benign cherry angiomas — small red vascular spots that appear on the skin with age.",
    products: "Clinical Removal Tools",
    results: "Clearer skin free from red angioma spots.",
  },

  // ─── LASER HAIR REMOVAL ─────────────────────────────────────────────────────
  {
    id: 11,
    category: 'Laser',
    name: "Upper Lip / Chin",
    price: "£35",
    time: "15 mins",
    image: "/images/laser.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Small area laser hair removal using Soprano Titanium — the gold standard in painless, permanent hair reduction.",
    products: "Soprano Titanium Special Edition",
    results: "Permanent hair reduction with no irritation or ingrown hairs.",
  },
  {
    id: 12,
    category: 'Laser',
    name: "Full Face Laser",
    price: "£80",
    time: "30 mins",
    image: "/images/laser.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Comprehensive facial laser hair removal covering upper lip, chin, sides of face and neck.",
    products: "Soprano Titanium",
    results: "Smooth, hair-free facial skin — no more threading or waxing.",
  },
  {
    id: 13,
    category: 'Laser',
    name: "Underarm Laser",
    price: "£45",
    time: "15 mins",
    image: "/images/laser.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Fast, virtually painless laser treatment for the underarm area using CoolTip technology.",
    products: "Soprano Titanium CoolTip",
    results: "No more shaving shadow, razor bumps or underarm irritation.",
  },
  {
    id: 14,
    category: 'Laser',
    name: "Full Body Laser",
    price: "£250",
    time: "90 mins",
    image: "/images/laser.jpg",
    modalImage: "/skincare/before-after.png",
    description: "The complete full-body laser hair removal session — safe for all skin types and tones.",
    products: "Soprano Titanium",
    results: "Total body smoothness and lasting hair-free confidence.",
  },
  {
    id: 15,
    category: 'Laser',
    name: "Men's Beard Line",
    price: "£50",
    time: "20 mins",
    image: "/images/laser.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Laser treatment to define the beard line and eliminate neck razor rash for clean, sharp results.",
    products: "Precision Laser Application",
    results: "Sharp beard definition with zero ingrown hairs.",
  },
  {
    id: 16,
    category: 'Laser',
    name: "Men's Full Back",
    price: "£140",
    time: "45 mins",
    image: "/images/laser.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Complete laser hair removal for the entire back and shoulder area.",
    products: "Soprano Titanium",
    results: "Smooth, permanently hair-free back and shoulders.",
  },
  {
    id: 17,
    category: 'Laser',
    name: "Men's Full Body",
    price: "£300",
    time: "120 mins",
    image: "/images/laser.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Head-to-toe laser hair removal tailored specifically for men's skin and hair types.",
    products: "Medical Grade Laser — Soprano Titanium",
    results: "Long-term reduction of dense body hair across all areas.",
  },

  // ─── HAIR & SCALP ───────────────────────────────────────────────────────────
  {
    id: 18,
    category: 'Hair',
    name: "Scalp Detox & Deep Clean",
    price: "£75",
    time: "45 mins",
    image: "/images/detox.jpg",
    modalImage: "/skincare/before-after.png",
    description: "A thorough scalp treatment that removes build-up, restores pH balance and unclogs hair follicles for a healthy scalp environment.",
    products: "Clarifying Scalp Solutions",
    results: "Unclogged follicles, reduced flakiness and a balanced, healthy scalp.",
  },
  {
    id: 19,
    category: 'Hair',
    name: "Hair Growth Microneedling",
    price: "£95",
    time: "60 mins",
    image: "/images/detox.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Targeted scalp microneedling to stimulate circulation, reactivate dormant follicles and encourage natural hair regrowth.",
    products: "Growth Factor Infusion + Microneedling",
    results: "Increased hair density, stronger strands and visible regrowth.",
  },

  // ─── PACKAGES ───────────────────────────────────────────────────────────────
  {
    id: 20,
    category: 'Packages',
    name: "Glow & Glass Skin Package",
    price: "£350",
    time: "Course of 3",
    image: "/images/about.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Our most popular skin transformation package — Hydrafacial + Dermaplaning + LED Light Therapy for the ultimate glass skin finish.",
    products: "CosMedix, Hydrafacial & LED Light Therapy",
    results: "Unmatched radiance, refined pores and lasting skin clarity.",
  },
  {
    id: 21,
    category: 'Packages',
    name: "Clear Skin & Acne Program",
    price: "£320",
    time: "Course of 3",
    image: "/images/about.jpg",
    modalImage: "/skincare/before-after.png",
    description: "A targeted combination of Chemical Peels and LED Light Therapy sessions specifically designed to combat active acne and congestion.",
    products: "Metabolic Peels + LED Light Therapy",
    results: "Cleared congestion, reduced acne bacteria and brighter skin.",
  },
  {
    id: 22,
    category: 'Packages',
    name: "Lift & Rejuvenation Program",
    price: "£380",
    time: "Course of 3",
    image: "/images/about.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Microneedling combined with LED Light Therapy to firm, lift and deeply rejuvenate ageing or tired skin.",
    products: "Collagen Induction + LED Light Therapy",
    results: "Tighter skin, softened wrinkles and a more youthful appearance.",
  },
  {
    id: 23,
    category: 'Packages',
    name: "Microneedling Course",
    price: "£300",
    time: "Course of 3",
    image: "/images/about.jpg",
    modalImage: "/skincare/before-after.png",
    description: "A bundle of three microneedling sessions for accelerated, visible skin transformation with compounding results.",
    products: "Medical Grade Needling",
    results: "Long-term firming, reduced scarring and overall skin transformation.",
  },
  {
    id: 24,
    category: 'Packages',
    name: "Underarm Laser Course",
    price: "£240",
    time: "Course of 6",
    image: "/images/laser.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Our best-value package for achieving permanent underarm hair reduction — six sessions for complete, lasting results.",
    products: "Soprano Titanium",
    results: "Complete, permanent hair removal in six sessions.",
  },
];