export const TREATMENTS = [

  // ─── ADVANCED SKIN ──────────────────────────────────────────────────────────
  {
    id: 1,
    category: 'Skin',
    name: "Signature Facial",
    price: "£95",
    time: "60 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Our bespoke facial designed to deep clean, exfoliate and nourish.",
    products: "CosMedix Benefit Clean, Purity Solution",
    results: "Immediate glow and hydrated skin texture.",
  },
  {
    id: 2,
    category: 'Skin',
    name: "Signature Facial + LED",
    price: "£120",
    time: "75 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Signature facial enhanced with Dermalux LED for deeper rejuvenation.",
    products: "CosMedix + Dermalux LED",
    results: "Boosted collagen and reduced redness.",
  },
  {
    id: 3,
    category: 'Skin',
    name: "Chemical Peel",
    price: "£99",
    time: "45 mins",
    image:"/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Medical-grade metabolic peels to resurface and renew the skin.",
    products: "CosMedix Metabolic Peels",
    results: "Improved tone and smoother fine lines.",
  },
  {
    id: 4,
    category: 'Skin',
    name: "Microneedling",
    price: "£110",
    time: "60 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Collagen Induction Therapy to treat scarring and texture.",
    products: "Sterile Micro-needling Technology",
    results: "Firmer skin and reduced acne scars.",
  },
  {
    id: 5,
    category: 'Skin',
    name: "Hydrafacial",
    price: "£110",
    time: "60 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",       
    description: "Cleanses, extracts, and hydrates using patented vortex technology.",
    products: "Vortex-Fusion Technology Serums",
    results: "Deeply cleaned pores and instant 'glass skin' finish.",
  },

  // ─── DERMAPLANING ───────────────────────────────────────────────────────────
  {
    id: 6,
    category: 'Skin',
    name: "Dermaplaning",
    price: "£65",
    time: "45 mins",
    image: "/skincare/dyee.jpg",
     modalImage: "/skincare/before-after.png",
    description: "Removal of dead skin and peach fuzz for a silky-smooth base.",
    products: "Surgical-grade Blade & Hydrating Mask",
    results: "Better product absorption and flawless makeup finish.",
  },

  // ─── LED LIGHT THERAPY ──────────────────────────────────────────────────────
  {
    id: 7,
    category: 'Skin',
    name: "LED Standalone",
    price: "£40",
    time: "30 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "DermaLux Tri-Wave MD — rejuvenation for all skin types.",
    products: "Multi-wavelength LED Technology",
    results: "Calmed inflammation and boosted skin health.",
  },

  // ─── SKIN LESION REMOVAL ────────────────────────────────────────────────────
  {
    id: 8,
    category: 'Skin',
    name: "Skin Tag Removal",
    price: "from £40",
    time: "30 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Safe and precise removal of unwanted skin tags.",
    products: "Medical Extraction Tools",
    results: "Clear, smooth skin surface.",
  },
  {
    id: 9,
    category: 'Skin',
    name: "Milia Removal",
    price: "from £50",
    time: "30 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Professional extraction of white milia seeds.",
    products: "Sanitized Precision Tools",
    results: "Removal of bumps around eyes and face.",
  },

  // ─── LASER HAIR REMOVAL (WOMEN) ─────────────────────────────────────────────
  {
    id: 10,
    category: 'Laser',
    name: "Upper Lip / Chin",
    price: "£35",
    time: "15 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Small area laser hair removal with Soprano Titanium.",
    products: "Soprano Titanium Special Edition",
    results: "Permanent hair reduction on facial areas.",
  },
  {
    id: 11,
    category: 'Laser',
    name: "Full Face Laser",
    price: "£80",
    time: "30 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Comprehensive facial hair removal including lip, chin, and sides.",
    products: "Soprano Titanium",
    results: "Smooth facial skin without threading/waxing.",
  },
  {
    id: 12,
    category: 'Laser',
    name: "Underarm Laser",
    price: "£45",
    time: "15 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Fast, painless laser for the underarm area.",
    products: "CoolTip Technology",
    results: "No more shaving shadow or irritation.",
  },
  {
    id: 13,
    category: 'Laser',
    name: "Full Body Laser",
    price: "£250",
    time: "90 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "The gold standard in hair removal — safe for all skin types.",
    products: "Soprano Titanium",
    results: "Total body smoothness and hair-free confidence.",
  },

  // ─── LASER HAIR REMOVAL (MEN) ───────────────────────────────────────────────
  {
    id: 14,
    category: 'Laser',
    name: "Men's Beard Line",
    price: "£50",
    time: "20 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Perfect for defining the beard line and reducing neck rash.",
    products: "Precision Laser Application",
    results: "Sharp beard lines and zero ingrown hairs.",
  },
  {
    id: 15,
    category: 'Laser',
    name: "Men's Full Back",
    price: "£140",
    time: "45 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Complete hair removal for the entire back area.",
    products: "Soprano Titanium",
    results: "Smooth, hair-free back and shoulders.",
  },
  {
    id: 16,
    category: 'Laser',
    name: "Men's Full Body",
    price: "£300",
    time: "120 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Head-to-toe laser hair removal tailored for men.",
    products: "Medical Grade Laser",
    results: "Long-term reduction of thick body hair.",
  },

  // ─── SIGNATURE PACKAGES ─────────────────────────────────────────────────────
  {
    id: 17,
    category: 'Skin',
    name: "Glow & Glass Skin Package",
    price: "£350",
    time: "Course of 3",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Hydrafacial + Dermaplaning + LED for the ultimate skin finish.",
    products: "CosMedix, Hydrafacial & Dermalux",
    results: "Unmatched radiance and skin clarity.",
  },
  {
    id: 18,
    category: 'Skin',
    name: "Clear Skin & Acne Program",
    price: "£320",
    time: "Course of 3",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Targeted Chemical Peel + LED sessions to combat active acne.",
    products: "Metabolic Peels + Phototherapy",
    results: "Cleared congestion and reduced acne bacteria.",
  },
  {
    id: 19,
    category: 'Skin',
    name: "Lift & Rejuvenation Program",
    price: "£380",
    time: "Course of 3",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Microneedling + LED to firm, lift and rejuvenate aging skin.",
    products: "Collagen Induction + Recovery LED",
    results: "Tighter skin and softened wrinkles.",
  },

  // ─── HAIR & SCALP ──────────────────────────────────────────────────────────
  {
    id: 20,
    category: 'Hair',
    name: "Scalp Detox & Deep Clean",
    price: "£75",
    time: "45 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Removes build-up and restores scalp balance.",
    products: "Clarifying Scalp Solutions",
    results: "Unclogged follicles and healthy scalp.",
  },
  {
    id: 21,
    category: 'Hair',
    name: "Hair Growth Microneedling",
    price: "£95",
    time: "60 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Stimulates scalp circulation to reactivate follicles.",
    products: "Growth Factor Infusion",
    results: "Increased hair density and strength.",
  },

  // ─── ADDITIONAL COURSES (SUMMARY) ───────────────────────────────────────────
  {
    id: 22,
    category: 'Packages',
    name: "Microneedling Course",
    price: "£300",
    time: "Course of 3",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Bundle of 3 microneedling sessions for accelerated results.",
    products: "Medical Grade Needling",
    results: "Long-term skin transformation.",
  },
  {
    id: 23,
    category: 'Laser',
    name: "Underarm Laser Course",
    price: "£240",
    time: "Course of 6",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Best value package for permanent underarm hair reduction.",
    products: "Soprano Titanium",
    results: "Complete hair removal in 6 sessions.",
  },
  {
    id: 24,
    category: 'Skin',
    name: "Cherry Angioma Removal",
    price: "from £40",
    time: "30 mins",
    image: "/skincare/dyee.jpg",
    modalImage: "/skincare/before-after.png",
    description: "Safe removal of red blood spots (Cherry Angiomas).",
    products: "Clinical Removal Tools",
    results: "Clearer skin without red spots.",
  }
];