export const allTreatments = [
  {
    title: "Laser Hair Removal",
    shortDesc: "Soprano Titanium Special Edition — virtually painless hair removal on all skin types, year-round.",
    fullDesc: "Soprano Titanium Special Edition combines ultimate functionality with ICE cold comfort for smarter, faster and virtually painless hair removal on all skin types. Suitable for all skin tones and most hair colours, it is the gold standard in permanent hair reduction.",
    slug: "laser-hair-removal",
    image: "/images/laser.jpg",
    duration: "30–60 min",
    price: "From £60",
  },
  {
    title: "DYE SVL & DYE VL IPL",
    shortDesc: "Harmony XL Pro Special Edition IPL for vascular and pigmented lesion treatment.",
    fullDesc: "Harmony XL Pro Special Edition IPL uses narrow-spectrum wavelengths to treat broad areas of vascular and pigmented lesions. Highly effective for rosacea, thread veins, age spots and sun damage.",
    slug: "dye-svl-dye-vl-ipl",
    image: "/images/dye.jpg",
    duration: "30–45 min",
    price: "From £150",
  },
  {
    title: "Chemical Peels",
    shortDesc: "Pure, non-irritating medical-grade peels safe enough to be repeated for any skin concern.",
    fullDesc: "We use only the purest, non-irritating medical-grade CosMedix peels that are safe enough to be repeated as needed to address any skin concern — from fine lines and hyperpigmentation to acne and uneven texture.",
    slug: "chemical-peels",
    image: "/images/chemical.jpg",
    duration: "45 min",
    price: "From £85",
  },
  {
    title: "DermaLux Tri-Wave MD",
    shortDesc: "Award-winning LED phototherapy to replenish, rejuvenate and repair your skin.",
    fullDesc: "Replenish, rejuvenate and repair your skin with this relaxing, clinically proven light treatment. DermaLux Tri-Wave MD delivers an instant radiance boost, reduces inflammation and accelerates healing for all skin types.",
    slug: "dermalux-tri-wave-md",
    image: "/images/dermalux.png",
    duration: "30 min",
    price: "From £55",
  },
  {
    title: "Bespoke Facials",
    shortDesc: "Thorough deep cleanse, gentle exfoliation and personalised treatment for your skin type.",
    fullDesc: "Our bespoke facial includes a thorough deep cleanse, gentle exfoliation, and the use of a facial steamer to open pores. Every facial is tailored to your individual skin concerns and goals using professional CosMedix products.",
    slug: "bespoke-facials",
    image: "/images/facial.jpg",
    duration: "60 min",
    price: "From £95",
  },
  {
    title: "Skin Analyser (Zemits)",
    shortDesc: "Advanced multi-spectrum skin analysis for accurate diagnosis and personalised treatment plans.",
    fullDesc: "Aesthetic consultations with Zemits Skin Analysis Technology use multi-spectrum imaging to provide accurate diagnosis and personalised treatment plans. Included free with any new client consultation.",
    slug: "skin-analyser-zemits",
    image: "/images/analysis.png",
    duration: "15 min",
    price: "FREE",
  },
  {
    title: "ClearLift",
    shortDesc: "Award-winning non-ablative laser facelift — the 'lunchtime' rejuvenation treatment.",
    fullDesc: "ClearLift is the most popular Harmony XL Pro treatment — award-winning and repeatedly viral on social media. Known as the lunchtime facelift, it delivers controlled dermal remodelling with zero downtime, tightening skin and reducing fine lines.",
    slug: "clear-lift",
    image: "/images/clearlift.png",
    duration: "60 min",
    price: "From £180",
  },
  {
    title: "ClearSkin",
    shortDesc: "Award-winning laser treatment targeting acne, oiliness and skin rejuvenation.",
    fullDesc: "ClearSkin is an award-winning laser treatment designed to treat oily skin and all forms of acne — including active breakouts, post-acne scarring and enlarged pores — whilst also delivering a gentle skin rejuvenating effect.",
    slug: "clear-skin",
    image: "/images/clear_skin.png",
    duration: "45 min",
    price: "POA",
  },
  {
    title: "Tattoo Removal",
    shortDesc: "Safe, precise laser tattoo removal for all ink colours on all skin types.",
    fullDesc: "Our laser tattoo removal treatments offer a safe and precise solution for erasing unwanted tattoos. Using advanced Q-switched laser technology, we target ink particles of all colours with minimal risk to the surrounding skin.",
    slug: "tattoo-removal",
    image: "/images/Tattoo-removal.jpg",
    duration: "15–30 min",
    price: "POA",
  },
  {
    title: "iPixel",
    shortDesc: "Fractional Erbium YAG laser resurfacing for scars, wrinkles and skin texture.",
    fullDesc: "The iPixel is a highly effective fractional ablative skin resurfacing treatment using an Erbium YAG laser at 2940nm wavelength. It dramatically improves acne scars, surgical scars, fine lines, wrinkles and overall skin texture.",
    slug: "ipixel",
    image: "/images/ipixel.jpg",
    duration: "60 min",
    price: "POA",
  },
];