export const allTreatments = [
  {
    title: "Laser Hair Removal",
    shortDesc: "Say goodbye to shaving, waxing and ingrown hairs for good. Our laser is virtually painless and works on all skin tones — yes, even darker ones.",
    fullDesc: "No more razors, no more waxing strips, no more ingrown hairs. Using the Soprano Titanium — one of the most advanced laser systems available — Sumi delivers virtually pain-free, permanent hair reduction on all skin types and tones, year-round. Most clients see a significant reduction after just a few sessions.",
    slug: "laser-hair-removal",
    image: "/images/laser.jpg",
    duration: "30–60 min",
    price: "From £35",
  },
  {
    title: "Chemical Peels",
    shortDesc: "Stubborn dullness, pigmentation or breakouts? A chemical peel cuts through it. Real results, no fluff — tailored every time to your skin.",
    fullDesc: "Chemical peels get a bad reputation — but done right, they're transformative. Sumi uses only CosMedix medical-grade peels that are gentle enough to repeat but strong enough to actually work. Whether you're dealing with pigmentation, acne, fine lines or just skin that's lost its spark, she'll tailor the peel precisely to what your skin needs.",
    slug: "chemical-peels",
    image: "/images/chemical.jpg",
    duration: "45 min",
    price: "From £85",
  },
  {
    title: "LED Light Therapy",
    shortDesc: "Lie back and let the light do the work. Seriously — zero downtime, zero discomfort, and your skin will genuinely thank you for it.",
    fullDesc: "LED Light Therapy is one of those treatments that sounds too good to be true — but the science is solid. Clinically proven wavelengths of light reduce inflammation, boost collagen production and accelerate skin healing. It's deeply relaxing, completely non-invasive and suits every skin type. Perfect as a standalone or bolted on to any treatment.",
    slug: "led-light-therapy",
    image: "/images/dermalux.png",
    duration: "30 min",
    price: "From £40",
  },
  {
    title: "Bespoke Facials",
    shortDesc: "Not a one-size-fits-all. Sumi will read your skin on the day and build the facial around exactly what it needs — nothing more, nothing less.",
    fullDesc: "No two facials here are the same. Sumi starts by looking at your skin — really looking — before selecting the right cleanse, exfoliation and treatment from the CosMedix clinical range. If your skin is dehydrated, she'll hydrate it. If it's congested, she'll clear it. It's a proper facial, done properly.",
    slug: "bespoke-facials",
    image: "/images/facial.jpg",
    duration: "60 min",
    price: "From £95",
  },
  {
    title: "Skin Analyser",
    shortDesc: "See what your skin is actually doing beneath the surface. Free for every new client — no obligation, no pressure.",
    fullDesc: "The Skin Analyser uses multi-spectrum imaging to show you exactly what's going on beneath the surface of your skin — things you'd never notice in the mirror. It's the first step for every new client at Sai Skin Care, completely free, and gives Sumi everything she needs to recommend a treatment plan that's actually right for you.",
    slug: "skin-analyser",
    image: "/images/analysis.png",
    duration: "15 min",
    price: "FREE",
  },
  {
    title: "ClearLift",
    shortDesc: "A genuine lift with zero downtime. Walk in on your lunch break, walk out looking like you've had a really long, good sleep.",
    fullDesc: "ClearLift has gone viral on social media — and for good reason. It's a non-surgical laser treatment that tightens skin, reduces fine lines and delivers real rejuvenation with absolutely zero downtime. No redness, no peeling, no hiding. You can come in on a Wednesday lunchtime and be back at your desk by afternoon. It's become one of the most-requested treatments at Sai Skin Care.",
    slug: "clear-lift",
    image: "/images/clearlift.png",
    duration: "60 min",
    price: "From £180",
  },
  {
    title: "ClearSkin",
    shortDesc: "Struggling with breakouts, oiliness or the scars they leave behind? ClearSkin goes after all of it at once — actively and gently.",
    fullDesc: "ClearSkin is one of the most effective laser treatments available for acne-prone skin. It targets active breakouts, persistent oiliness, enlarged pores and post-acne scarring — all in a single session. Unlike harsh topical treatments, it works beneath the surface to reduce bacteria and calm the skin while delivering a gentle rejuvenating effect. Many clients notice a visible improvement after just one session.",
    slug: "clear-skin",
    image: "/images/clear_skin.png",
    duration: "45 min",
    price: "POA",
  },
  {
    title: "DYE SVL & DYE VL IPL",
    shortDesc: "Redness, rosacea, thread veins or sun damage? This IPL treatment targets the root cause — not just the surface.",
    fullDesc: "If you've been living with rosacea, thread veins, persistent redness or sun-damaged skin, DYE SVL and DYE VL IPL treatments can make a real difference. The Harmony XL Pro uses narrow-spectrum light to precisely target vascular and pigmented lesions without harming the surrounding skin — leaving your complexion clearer and more even over a course of sessions.",
    slug: "dye-svl-dye-vl-ipl",
    image: "/images/dye.jpg",
    duration: "30–45 min",
    price: "From £150",
  },
  {
    title: "Tattoo Removal",
    shortDesc: "Changed your mind? We don't judge. Safe, precise laser removal that works on all ink colours — including the stubborn ones.",
    fullDesc: "Whether it's a name you'd rather forget or a design you've outgrown, laser tattoo removal at Sai Skin Care is safe, precise and gets results. Using Q-switched laser technology, Sumi breaks down ink particles of all colours with minimal risk to the surrounding skin. Fading happens gradually across sessions, and a free consultation will give you a realistic picture of what to expect.",
    slug: "tattoo-removal",
    image: "/images/Tattoo-removal.jpg",
    duration: "15–30 min",
    price: "POA",
  },
  {
    title: "iPixel",
    shortDesc: "For scars, deep lines and skin texture that nothing else has touched — iPixel resurfaces at a level most treatments simply can't reach.",
    fullDesc: "iPixel is one of the most powerful skin resurfacing treatments available. If you've tried creams, facials and peels and still can't shift acne scars, surgical scars, deep wrinkles or rough texture — this is the treatment that can actually make the difference. It uses a fractional Erbium YAG laser to resurface the skin at depth, triggering significant collagen remodelling. Results are visible and, for many clients, life-changing.",
    slug: "ipixel",
    image: "/images/ipixel.jpg",
    duration: "60 min",
    price: "POA",
  },
];