export const allTreatments = [
  {
    title: "Laser Hair Removal",
    shortDesc: "Soprano Titanium Special Edition — virtually painless, permanent hair reduction on all skin types and tones, year-round.",
    fullDesc: "Soprano Titanium Special Edition combines ultimate functionality with ICE cold comfort technology for smarter, faster and virtually painless hair removal on all skin types. Suitable for all skin tones and most hair colours, it is the gold standard in permanent hair reduction.",
    slug: "laser-hair-removal",
    image: "/images/laser.jpg",
    duration: "30–60 min",
    price: "From £35",
  },
  {
    title: "Chemical Peels",
    shortDesc: "Pure, non-irritating medical-grade CosMedix peels for brighter skin, clearer tone and fewer fine lines.",
    fullDesc: "We use only the purest, non-irritating medical-grade CosMedix peels that are safe enough to be repeated as needed. Whether you're dealing with fine lines, hyperpigmentation, acne or uneven texture — our peels are tailored precisely to your skin.",
    slug: "chemical-peels",
    image: "/images/chemical.jpg",
    duration: "45 min",
    price: "From £85",
  },
  {
    title: "LED Light Therapy",
    shortDesc: "Clinically proven light therapy to rejuvenate, repair and calm all skin types with zero downtime.",
    fullDesc: "Replenish, rejuvenate and repair your skin with this relaxing, clinically proven light treatment. Delivering an instant radiance boost, it reduces inflammation, accelerates skin healing and is suitable for all skin types with no recovery time.",
    slug: "led-light-therapy",
    image: "/images/dermalux.png",
    duration: "30 min",
    price: "From £40",
  },
  {
    title: "Bespoke Facials",
    shortDesc: "A personalised deep cleanse, exfoliation and nourishing facial tailored to your unique skin type and goals.",
    fullDesc: "Our bespoke facial includes a thorough deep cleanse, gentle exfoliation and the use of a facial steamer to open pores. Every facial is individually tailored to your skin concerns using professional CosMedix clinical products.",
    slug: "bespoke-facials",
    image: "/images/facial.jpg",
    duration: "60 min",
    price: "From £95",
  },
  {
    title: "Skin Analyser",
    shortDesc: "Advanced multi-spectrum skin analysis for accurate diagnosis and a personalised treatment plan.",
    fullDesc: "Our Skin Analyser uses multi-spectrum imaging technology to provide an in-depth diagnosis of your skin's condition — identifying concerns invisible to the naked eye. Included free with every new client consultation.",
    slug: "skin-analyser",
    image: "/images/analysis.png",
    duration: "15 min",
    price: "FREE",
  },
  {
    title: "ClearLift",
    shortDesc: "The award-winning, zero-downtime laser facelift — known as the lunchtime rejuvenation treatment.",
    fullDesc: "ClearLift is the most popular Harmony XL Pro treatment — award-winning and repeatedly viral on social media. Known as the lunchtime facelift, it delivers controlled dermal remodelling with zero downtime, tightening skin and reducing fine lines.",
    slug: "clear-lift",
    image: "/images/clearlift.png",
    duration: "60 min",
    price: "From £180",
  },
  {
    title: "ClearSkin",
    shortDesc: "Award-winning laser treatment targeting active acne, oiliness, enlarged pores and post-acne scarring.",
    fullDesc: "ClearSkin is an award-winning laser treatment designed to treat oily skin and all forms of acne — including active breakouts, post-acne scarring and enlarged pores — whilst also delivering a gentle skin rejuvenating effect.",
    slug: "clear-skin",
    image: "/images/clear_skin.png",
    duration: "45 min",
    price: "POA",
  },
  {
    title: "DYE SVL & DYE VL IPL",
    shortDesc: "Harmony XL Pro narrow-spectrum IPL for vascular lesions, rosacea, thread veins and sun damage.",
    fullDesc: "Harmony XL Pro Special Edition IPL uses narrow-spectrum wavelengths to treat broad areas of vascular and pigmented lesions. Highly effective for rosacea, thread veins, age spots and sun damage across all skin types.",
    slug: "dye-svl-dye-vl-ipl",
    image: "/images/dye.jpg",
    duration: "30–45 min",
    price: "From £150",
  },
  {
    title: "Tattoo Removal",
    shortDesc: "Safe, precise laser tattoo removal for all ink colours on all skin types with minimal surrounding skin risk.",
    fullDesc: "Our laser tattoo removal treatments offer a safe and precise solution for erasing unwanted tattoos. Using advanced Q-switched laser technology, we target ink particles of all colours with minimal risk to the surrounding skin.",
    slug: "tattoo-removal",
    image: "/images/Tattoo-removal.jpg",
    duration: "15–30 min",
    price: "POA",
  },
  {
    title: "iPixel",
    shortDesc: "Fractional Erbium YAG laser resurfacing — dramatically improves scars, wrinkles and skin texture.",
    fullDesc: "The iPixel is a highly effective fractional ablative skin resurfacing treatment using an Erbium YAG laser at 2940nm. It dramatically improves acne scars, surgical scars, fine lines, wrinkles and overall skin texture with visible results.",
    slug: "ipixel",
    image: "/images/ipixel.jpg",
    duration: "60 min",
    price: "POA",
  },
];